# exit: terminates the DCI network (vrf104100) and routes it into the
# inter-partition core on swp2. DCI devices sized for SRv6 (9000 + 48 B).
waitInterfaces: [swp1, swp2]
loopback: [10.0.0.14/32]
vrfs:
  - {name: vrf104100, table: 1001}
bridge: {name: bridge, mtu: 9166}
vnis:
  - {vni: 104100, vlan: 1001, vrf: vrf104100, local: 10.0.0.14, mtu: 9166}
interfaces:
  - {name: swp1, mtu: 9216}
  - {name: swp2, vrf: vrf104100, mtu: 9216}
